config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin', :sign_out => 'logout'}, only: [:sessions]

  resources :categories do
    resources :products do
      resources :images
    end
  end

  root 'pages#home'
  get 'contacts', to: 'pages#contacts', as: 'contacts'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, ImageUploader
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images
  belongs_to :category

  validates :name, :category_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_categories

  protected

  def set_categories
    @categories = Category.all.order(:order)
  end

  def authenticate_admin!
    if admin_signed_in?
      super
    else
      redirect_to root_path, notice: 'Ви повинні бути адміном!'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy]

  def index
    @categories = Category.all.order(:order)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @categories.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'categories was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :order)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @images = @product.images
  end

  def new
    @product = Product.find(params[:product_id])
    @image = @product.images.build
  end

  def create
    @product = Product.find(params[:product_id])
    @image = @product.images.build(images_params)

    respond_to do |format|
      if @image.save!
        format.html { redirect_to category_product_path(@product.category, @product)}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def images_params
      params.require(:image).permit(:file)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.all.limit(6)
    @initial_images = @products.map{|p| p.images.map{|i| i.file.url}}.flatten
  end

  def contacts
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:index, :create]
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy]

  def index
    @products = @category.products.paginate(page: params[:page], per_page: 6)
  end

  def show
    @product = Product.find(params[:id])
    @images = @product.images
  end

  def new
    @product = Product.new
    @image = @product.images.build
  end

  def edit
  end

  def create
    @product = @category.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Продукт був успішно створений' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to category_product_path(@product.category, @product), notice: 'Продукт був успішно збережений' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :category_id, images_attributes: [:product_id, :url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :order
    = f.number_field :order, class: 'form-control'
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Зберегти'

app/views/categories/edit.html.haml
%h1 Редагування категорії - #{@category.name}
%br
= render 'form'

app/views/categories/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Порядок відображення
      %th Назва
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td=category.order
        %td=category.name
        %td
          = link_to edit_category_path(category) do
            %i.glyphicon.glyphicon-edit
        %td
          = link_to category, :method => :delete, :data => { :confirm => 'Are you sure?' } do
            %i.glyphicon.glyphicon-remove

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/images/index.html.haml
/ %h1
/   = "Зображення для продукту #{@product.name}"

/ = link_to 'New Image', new_product_image_path
/ %table
/   %thead
/     %tr
/       %th Name
/       %th Description
/       %th
/       %th
/       %th

/   %tbody
/     - @images.each do |image|
/       %tr
/         %td=image_tag image.file.url, html: {width: '150'}
/         %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

app/views/images/new.html.haml
= form_for [@product.category, @product, @image] do |f|
  = f.label :file
  = f.file_field :file

  = f.submit 'submit'

app/views/layouts/_footer.html.haml
%footer
  .row
    .col-lg-12
      %p Ярослав Кобрин © Шафа Сайт 2016

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Шафа-Купе
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Головна', root_path
        %li
          / = link_to 'Каталог', products_path
        %li
          %a{href: '#'} Партнери
        %li
          %a{href: '/contacts'} Контакти
        - if admin_signed_in?
          %li
            = link_to 'Категорії товарів', categories_path
          %li
            = link_to('Вийти ', destroy_admin_session_path, method: :delete)

app/views/layouts/_left_nav.html.haml
.list-group
  - @categories.each do |category|
    = link_to category.name, category_products_path(category), class: "list-group-item"

%br
- if admin_signed_in?
  .right-button
    = link_to 'Додати категорію', new_category_path, { class: 'btn btn-success' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shafa
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .main-container
      = render 'layouts/header'
      .container
        .row
          .col-md-3
            = render 'layouts/left_nav'
          .col-md-9
            = yield
      .container
        = render 'layouts/footer'

app/views/pages/contacts.html.haml
Головний офіс
тел.факс 8(0352) 42-10-07

app/views/pages/home.html.haml
.row.carousel-holder
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    %ol.carousel-indicators
      - @initial_images.each_with_index do |url, index|
        %li{"data-slide-to" => index, "data-target" => "#carousel-example-generic", class: "#{index == 0 ? 'active' : ''}"}
    .carousel-inner
      - @initial_images.each_with_index do |url, index|
        .item{class: "#{index == 0 ? 'active' : ''}"}
          = image_tag(url, style:"height:300px;" )
    %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic"}
      %span.glyphicon.glyphicon-chevron-left
    %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic"}
      %span.glyphicon.glyphicon-chevron-right
.row
  - @products.each do |product|
    .col-sm-4.col-lg-4.col-md-4
      .thumbnail
        .img{style:"height:122px;" }
          - if product.images.count > 0
            = image_tag(product.images.first.file.url)
          - else
            = image_tag("http://placehold.it/320x150")
        .caption
          / %h4.pull-right $24.99
          %h4
            = link_to category_product_path(product.category.id, product.id) do
              %span.name
                = product.name
          %p
            = product.description

app/views/products/_form.html.haml
= form_for [@product.category, @product] do |f|
  .form-group
    = f.label "Назва"
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label "Опис"
    = f.text_area :description, class: 'form-control'

  .form-group
    = f.label 'Категорія'
    = f.collection_select :category_id, Category.all, :id, :name, {}, class: 'form-control'

  = f.submit 'Зберегти', class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 Редагування інформації

= render 'form'

app/views/products/index.html.haml
.buttons-panel
  - if admin_signed_in?
    .right-button
      = link_to 'Додати новий продукт', new_category_product_path, { class: 'btn btn-primary' }
  .left-button
    = will_paginate @products, renderer: BootstrapPagination::Rails

.row
  - @products.each do |product|
    .col-sm-4.col-lg-4.col-md-4
      .thumbnail
        .img{style:"height:122px;" }
          - if product.images.count > 0
            = image_tag(product.images.first.file.url)
          - else
            = image_tag("http://placehold.it/320x150")
        .caption
          / %h4.pull-right $24.99
          %h4
            = link_to category_product_path(product.category.id, product.id) do
              %span.name
                = product.name
          %p
            = product.description

    / - @products.each do |product|
    /   .col-md-6.col-xs-12.collection
    /     %a{href: "/products/#{product.id}"}
    /       .landidng-product
    /         - if product.images.count > 0
    /           = image_tag("#{product.images.first.file.url}")
    /         - else
    /           = image_tag("https://placeholdit.imgix.net/~text?txtsize=80&txt=empty&w=850&h=550")
    /         %span.name
    /           = product.name

app/views/products/new.html.haml
%h1 Новий продукт

= render 'form'

app/views/products/show.html.haml
/ = link_to 'Назад до всіх продуктів', products_path
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description

= link_to 'Редагувати', edit_category_product_path(@product.category, @product)


%br
  = link_to 'Завантажити зображення', new_category_product_image_path(@product.category, @product)
%h1 Зображення
#links
  - @images.each do |image|
    %a{"data-gallery" => "", :href => "#{image.file.url}", :title => "Banana"}
      %img{:alt => "Banana", :src => "#{image.file.url(:thumb)}", width: '50'}

#blueimp-gallery.blueimp-gallery
  .slides
  %h3.title
  %a.prev ‹
  %a.next ›
  %a.close ×
  %a.play-pause
  %ol.indicator
  .modal.fade
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", type: "button"} &times;
          %h4.modal-title
        .modal-body.next
        .modal-footer
          %button.btn.btn-default.pull-left.prev{type: "button"}
            %i.glyphicon.glyphicon-chevron-left
            Previous
          %button.btn.btn-primary.next{type: "button"}
            Next
            %i.glyphicon.glyphicon-chevron-right